marks=[78, 85, 62, 90, 55, 88]
print("Marks: "+str(marks))
print("Highest Mark: "+str(max(marks)))
print("Lowest Mark: "+str(min(marks)))
print("Average Mark: "+str(sum(marks)/len(marks)))
print("Marks greater than 75: "+str([mark for mark in marks if mark>75]))
marks.append(95)
print("Marks after appending: "+str(marks)) 
marks.remove(55)
print("Marks after removing 55: "+str(marks))
print("Length of marks list: "+str(len(marks)))
print("Sorted Marks: "+str(sorted(marks)))
marks.sort(reverse=True)
print("Marks after sorting in descending order: "+str(marks))