numbers=[1,2,3,4,5,6,7,8,9]
print("len(numbers) "+str(len(numbers)))
numbers.append(10)
print("numbers.append(10) "+str(numbers))
numbers.insert(0,0)
print("numbers.insert(0,0) "+str(numbers))
numbers.remove(5)
print("numbers.remove(5) "+str(numbers))
numbers.pop()
print("numbers.pop() "+str(numbers))    
numbers.pop(1)
print("numbers.pop(1) "+str(numbers))
numbers.sort(reverse=True)
print("numbers.sort(reverse=True) "+str(numbers))
numbers.reverse()
print("numbers.reverse() "+str(numbers))
print("numbers.index(4) "+str(numbers.index(4)))
print("numbers.count(3) "+str(numbers.count(3)))
numbers.extend([11,12,13])
print("numbers.extend([11,12,13]) "+str(numbers))
print("sum(numbers) "+str(sum(numbers)))
print("max(numbers) "+str(max(numbers)))
print("min(numbers) "+str(min(numbers)))
numbers.clear() 
print("numbers.clear() "+str(numbers))
